config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  resources :products do
    member do
      put 'like', to: 'products#upvote'
      put 'dislike', to: 'products#downvote'
    end
  end
  resources :categories
  resources :users, only: [:index, :show]
  root 'pages#index'

  get 'my_products', to: 'products#my_products'
  # get 'search_products', to: 'products#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  include Paperclip::Glue
  belongs_to :user
  belongs_to :category

  acts_as_votable

  has_attached_file :image, styles: { medium: "300x300#", thumb: "150x150#" },
                    :storage => :cloudinary, :path => 'market-management/products/:filename',
                    :cloudinary_credentials => Rails.root.join("config/cloudinary.yml")
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :name, :description, :category_id, presence: true
  validates :description, length: { maximum: 2000 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  # belongs_to :role
  # before_create :set_default_role
  has_many :categories, dependent: :destroy
  has_many :products, dependent: :destroy

  include Paperclip::Glue

  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "150x150#" },
                    :storage => :cloudinary, :path => 'market-management/avatars/:filename',
                    :cloudinary_credentials => Rails.root.join("config/cloudinary.yml")
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :name, :email, presence: true

  # private
  #   def set_default_role
  #     self.role ||= Role.find_by_name('user')
  #   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :admin, :short_bio, :avatar])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  layout 'app-user'

  def index
    @categories = Category.all
  end

  def show
    @users = User.all
    @category = Category.find(params[:id])
    @products = Product.where(category_id: @category).paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
  end

  def new
    @category = current_user.categories.build
  end

  def edit
  end

  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to products_path, notice: 'category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to products_path, notice: 'category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # @random_product = Product.order("rand()").limit(3)
    @products = Product.limit(6).order("RANDOM()")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  layout 'app-user'

  def index
    @users = User.all

    if params[:category].blank?
      @products = Product.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @products = Product.where(category_id: @category_id).paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    end
  end

  def show
    @products = Product.limit(6).order("RANDOM()")
  end

  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_products
    @users = User.all
    @products = current_user.products.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
  end

  def upvote
    @product = Product.find(params[:id])
    @product.upvote_by current_user
    redirect_back(fallback_location: products_path)
  end

  def downvote
    @product = Product.find(params[:id])
    @product.downvote_by current_user
    redirect_back(fallback_location: products_path)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :category_id, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'app-user'

  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @products = Product.where(user_id: @user).paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info'}[flash_type] || flash_type.to_s
    # case flash_type
    #   when :success
    #     "alert-success"
    #   when :error
    #     "alert-danger"
    #   when :alert
    #     "alert-warning"
    #   when :notice
    #     "alert-info"
    #   else
    #     flash_type.to_s
    #   end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name, input_html: { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.button :submit, class: "btn-default" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', product: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td>
          <%= link_to 'Show', category, class: "btn btn-sm btn-default" %>
          <%= link_to 'Edit', edit_category_path(category), class: "btn btn-sm btn-default" %>
          <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h3>Products</h3>
    <% @products.each do |product| %>
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img class="media-object" width="200" height="200" src="<%= image_path product.image.url %><%#= cl_image_path(product.image.url(:original), :secure => true) %>" alt="<%= product.name %>">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <!-- Product name -->
            <%= product.name %>

            <div class="pull-right">
              <div class="btn-group">
                <!-- Like product -->
                <%= link_to like_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-up" %>
                  <%= product.get_upvotes.size %>
                <% end %>

                <!-- Dislike product -->
                <%= link_to dislike_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-down" %>
                  <%= product.get_downvotes.size %>
                <% end %>
              </div>

              <!-- Check product created by user == user_id -->
              <% if product.user == current_user -%>
                <div class="btn-group">
                  <%= link_to product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %>
                    <%= fa_icon "trash" %>
                  <% end %>

                  <%= link_to edit_product_path(product), class: "btn btn-primary btn-xs" do %>
                    <%= fa_icon "pencil" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </h4>
          <p>
            <span class="text-capitalize">
              <%= time_ago_in_words(product.created_at) %>
            </span> ago by
            <strong>
              <%= link_to product.user.name, user_path(product) %>
            </strong>
            -
            <strong>
              <%= link_to product.category.name, category_path(product) %></strong></small>
            </strong>
          </p>
          <%= simple_format truncate((product.description), length: 350, omission: '... ') { link_to "Continue Read", product_path(product) } %>
        </div>
      </div>
      <hr/>
    <% end %>
    <div class="digg_pagination">
      <%= will_paginate @products, :container => false %>
    </div>
  </div>

  <div class="col-md-4">
    <h3>Categories</h3>
    <div class="list-group">
      <% Category.all.each do |category| %>
        <%= link_to products_path(category: category.name), class: "list-group-item" do %>
          <span class="badge">
            <%= category.products.count %>
          </span>
          <%= category.name %>
        <% end %>
      <% end %>
    </div>

    <h3>Sellers</h3>
    <div class="list-group">
      <% @users.take(5).each do |user| %>
        <%= link_to user_path(user), class: "list-group-item" do %>
          <span class="badge">
            <%= user.products.count %>
          </span>
          <%= user.name %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/app-user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Market Management</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="<%= root_path %>" class="navbar-brand">Sunday Market</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to "All Users", users_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to "All Products", products_path %>
                </li>
                <% if user_signed_in? %>
                  <li>
                    <%= link_to "New Product", new_product_path %>
                  </li>
                  <li>
                    <%= link_to "My Product", my_products_path %>
                  </li>
                <% end %>
              </ul>
            </li>
            <% if user_signed_in? %>
              <% if current_user.admin? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "New Category", new_category_path %>
                    </li>
                  </ul>
                </li>
              <% end %>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Profile", edit_user_registration_path %>
                  </li>
                  <li>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li>
                <%= link_to "Login", new_user_session_path %>
              </li>
              <li>
                <%= link_to "Register", new_user_registration_path %>
              </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= render partial: "shared/flash_messages", flash: flash %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Sunday Market Management</h1>
  <p>Kombucha letterpress leggings mlkshk keytar pop-up poke deep v normcore. </p>
  <p>
    <% if user_signed_in? %>
      <%= link_to "All Products", products_path, class: "btn btn-primary btn-lg" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger btn-lg" %>
    <% else %>
      <%= link_to "All Products", products_path, class: "btn btn-primary btn-lg" %>
      <%= link_to "Join as Seller", new_user_registration_path, class: "btn btn-success btn-lg" %>
    <% end %>
  </p>
</div>

<div class="container">
  <h2>Random Product</h2>
  <hr>
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="thumbnail">
          <img class="img-responsive" src="<%= image_path product.image.url %><%#= cl_image_path(product.try(:image), :secure => true) %>" alt="<%= product.try(:name) %>">
          <div class="caption">
            <h3><%= product.try(:name) %></h3>
            <p><%= simple_format(truncate(product.try(:description), length: 250, omission: '... ') { link_to "Continue Read", product_path(product) }) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h3>Products</h3>
    <% @products.each do |product| %>
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img class="media-object" width="200" height="200" src="<%= cl_image_path(product.image.url(:original), :secure => true) %>" alt="<%= product.name %>">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <!-- Product name -->
            <%= product.name %>

            <div class="pull-right">
              <div class="btn-group">
                <!-- Like product -->
                <%= link_to like_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-up" %>
                  <%= product.get_upvotes.size %>
                <% end %>

                <!-- Dislike product -->
                <%= link_to dislike_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-down" %>
                  <%= product.get_downvotes.size %>
                <% end %>
              </div>

              <!-- Check product created by user == user_id -->
              <% if product.user == current_user -%>
                <div class="btn-group">
                  <%= link_to product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %>
                    <%= fa_icon "trash" %>
                  <% end %>

                  <%= link_to edit_product_path(product), class: "btn btn-primary btn-xs" do %>
                    <%= fa_icon "pencil" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </h4>
          <p>
            <span class="text-capitalize">
              <%= time_ago_in_words(product.created_at) %>
            </span> ago by
            <strong>
              <%= link_to product.user.name, user_path(product) %>
            </strong>
            -
            <strong>
              <%= link_to product.category.name, category_path(product) %></strong></small>
            </strong>
          </p>
          <%= simple_format truncate((product.description), length: 350, omission: '... ') { link_to "Continue Read", product_path(product) } %>
        </div>
      </div>
      <hr/>
    <% end %>
    <div class="digg_pagination">
      <%= will_paginate @products, :container => false %>
    </div>
  </div>

  <div class="col-md-4">
    <h3>Categories</h3>
    <div class="list-group">
      <% Category.all.each do |category| %>
        <%= link_to products_path(category: category.name), class: "list-group-item" do %>
          <span class="badge">
            <%= category.products.count %>
          </span>
          <%= category.name %>
        <% end %>
      <% end %>
    </div>

    <h3>Sellers</h3>
    <div class="list-group">
      <% @users.take(5).each do |user| %>
        <%= link_to user_path(user), class: "list-group-item" do %>
          <span class="badge">
            <%= user.products.count %>
          </span>
          <%= user.name %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="row">
  <div class="col-md-8">
    <h3>Products</h3>
    <% @products.each do |product| %>
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img class="media-object" width="200" height="200" src="<%= cl_image_path(product.image, :secure => true) %>" alt="<%= product.name %>">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <%= product.name %>

            <div class="pull-right">
              <div class="btn-group">
                <!-- Like product -->
                <%= link_to like_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-up" %>
                  <%= product.get_upvotes.size %>
                <% end %>

                <!-- Dislike product -->
                <%= link_to dislike_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-down" %>
                  <%= product.get_downvotes.size %>
                <% end %>
              </div>

              <!-- Check product created by user == user_id -->
              <% if product.user == current_user -%>
                <div class="btn-group">
                  <%= link_to product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %>
                    <%= fa_icon "trash" %>
                  <% end %>

                  <%= link_to edit_product_path(product), class: "btn btn-primary btn-xs" do %>
                    <%= fa_icon "pencil" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </h4>
          <p>
            <span class="text-capitalize">
              <%= time_ago_in_words(product.created_at) %>
            </span> ago by
            <strong>
              <%= link_to product.user.name, user_path(product) %>
            </strong>
            -
            <strong>
              <%= link_to product.category.name, category_path(product) %></strong></small>
            </strong>
          </p>
          <%= simple_format(product.description) %>
        </div>
      </div>
      <hr/>
    <% end %>
    <div class="digg_pagination">
      <%= will_paginate @products, :container => false %>
    </div>
  </div>

  <div class="col-md-4">
    <h3>Categories</h3>
    <div class="list-group">
      <% Category.all.each do |category| %>
        <%= link_to products_path(category: category.name), class: "list-group-item" do %>
          <span class="badge">
            <%= category.products.count %>
          </span>
          <%= category.name %>
        <% end %>
      <% end %>
    </div>

    <h3>Sellers</h3>
    <div class="list-group">
      <% @users.each do |user| %>
        <%= link_to user_path(user), class: "list-group-item" do %>
          <span class="badge">
            <%= user.products.count %>
          </span>
          <%= user.name %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-3">
        <img class="img-responsive" src="<%= image_path @product.image.url %>" alt="<%= @product.name %>">
      </div>
      <div class="col-xs-9">
        <h1>
          <%= @product.name %>

          <div class="pull-right">
            <div class="btn-group">
              <!-- Like product -->
              <%= link_to like_product_path(@product), method: :put, class: "btn btn-default btn-xs" do %>
                <%= fa_icon "thumbs-o-up" %>
                <%= @product.get_upvotes.size %>
              <% end %>

              <!-- Dislike product -->
              <%= link_to dislike_product_path(@product), method: :put, class: "btn btn-default btn-xs" do %>
                <%= fa_icon "thumbs-o-down" %>
                <%= @product.get_downvotes.size %>
              <% end %>
            </div>

            <!-- Check product created by user == user_id -->
            <% if @product.user == current_user -%>
              <div class="btn-group">
                <%= link_to product_path(@product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %>
                  <%= fa_icon "trash" %>
                <% end %>

                <%= link_to edit_product_path(@product), class: "btn btn-primary btn-xs" do %>
                  <%= fa_icon "pencil" %>
                <% end %>
              </div>
            <% end %>
          </div>
        </h1>
        <p>
          <span class="text-capitalize">
            <%= time_ago_in_words(@product.created_at) %>
          </span> ago by
          <strong>
            <%= link_to @product.user.name, user_path(@product) %>
          </strong>
          -
          <strong>
            <%= link_to @product.category.name, category_path(@product) %></strong></small>
          </strong>
        </p>
        <div>
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
              <a href="#description" aria-controls="description" role="tab" data-toggle="tab">Description</a>
            </li>
          </ul>
          <div class="tab-content panel-body">
            <div role="tabpanel" class="tab-pane active" id="description">
              <%= simple_format(@product.description) %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <%= link_to 'Back', products_path, class: "btn btn-default" %>
  </div>
</div>



<hr/>

<h2>Random Product</h2>
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <div class="thumbnail">
        <img class="img-responsive" width="250" height="250" src="<%= image_path product.image.url %><%#= cl_image_path(product.try(:image), :secure => true) %>" alt="<%= product.try(:name) %>">
        <div class="caption">
          <h3><%= product.try(:name) %></h3>
          <p><%= simple_format(truncate(product.try(:description), length: 250, omission: '... ') { link_to "Continue Read", product_path(product) }) %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="media">
          <div class="media-left">
            <a href="">
              <% if @user.avatar.present? %>
                <img class="media-object img-circle" width="100" height="100" src="<%= image_path @user.avatar.url %>" alt="<%= @user.name %>">
              <% else %>
                <img class="media-object img-circle" width="100" height="100" src="<%= image_path('blank-user.jpg') %>" alt="<%= @user.name %>">
              <% end %>
            </a>
          </div>
          <div class="media-body">
            <h4 class="media-heading"><%= link_to @user.name, user_path(@user) %></h4>
            <h5><%= @user.short_bio %></h5>
            <small><%= @user.email %></small> <br/>
            <% if @user.products.present? %>
              <small>Your products <%= @user.products.count %></small>
            <% else %>
              <small><strong><%= @user.name %></strong> don't have any product right now.</small>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h3>Products</h3>
    <% @products.each do |product| %>
      <div class="media">
        <div class="media-left">
          <a href="#">
            <img class="media-object" width="200" height="200" src="<%= cl_image_path(product.image.url(:original), :secure => true) %>" alt="<%= product.name %>">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">
            <!-- Product name -->
            <%= product.name %>

            <div class="pull-right">
              <div class="btn-group">
                <!-- Like product -->
                <%= link_to like_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-up" %>
                  <%= product.get_upvotes.size %>
                <% end %>

                <!-- Dislike product -->
                <%= link_to dislike_product_path(product), method: :put, class: "btn btn-default btn-xs" do %>
                  <%= fa_icon "thumbs-o-down" %>
                  <%= product.get_downvotes.size %>
                <% end %>
              </div>

              <!-- Check product created by user == user_id -->
              <% if product.user == current_user -%>
                <div class="btn-group">
                  <%= link_to product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" do %>
                    <%= fa_icon "trash" %>
                  <% end %>

                  <%= link_to edit_product_path(product), class: "btn btn-primary btn-xs" do %>
                    <%= fa_icon "pencil" %>
                  <% end %>
                </div>
              <% end %>
            </div>
          </h4>
          <p>
            <span class="text-capitalize">
              <%= time_ago_in_words(product.created_at) %>
            </span> ago by
            <strong>
              <%= link_to product.user.name, user_path(product) %>
            </strong>
            -
            <strong>
              <%= link_to product.category.name, category_path(product) %></strong></small>
            </strong>
          </p>
          <%= simple_format truncate((product.description), length: 350, omission: '... ') { link_to "Continue Read", product_path(product) } %>
        </div>
      </div>
      <hr/>
    <% end %>
    <div class="digg_pagination">
      <%= will_paginate @products, :container => false %>
    </div>
  </div>

  <div class="col-md-4">
    <h3>Categories</h3>
    <div class="list-group">
      <% Category.all.each do |category| %>
        <%= link_to products_path(category: category.name), class: "list-group-item" do %>
          <span class="badge">
            <%= category.products.count %>
          </span>
          <%= category.name %>
        <% end %>
      <% end %>
    </div>

    <h3>Sellers</h3>
    <div class="list-group">
      <% @users.take(5).each do |user| %>
        <%= link_to user_path(user), class: "list-group-item" do %>
          <span class="badge">
            <%= user.products.count %>
          </span>
          <%= user.name %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>